version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: laravel_app
    volumes:
      - ./:/var/www/html  # Mounts the current directory
      - ./apache/httpd.conf:/etc/apache2/sites-available/000-default.conf
      - ./storage:/var/www/html/storage
    ports:
      - "8000:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel-net
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        apt-get update && \
        apt-get install -y curl unzip && \
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
        docker-php-ext-install pdo pdo_mysql && \
        a2enmod rewrite && \
        apache2-foreground

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel-net

volumes:
  db_data:

networks:
  laravel-net: